### ISSUE TITLE
Harmonize hdmi_timings in /boot/config.txt and runcommand-onend.sh 

### ISSUE THREAD

**Issue by arcadeforge** [crtpi/CRTPi-RGB#1]
Thanks for the great work.

I wanted to to point you to the /boot/config.txt and runcommand-onend.sh

Both have a different hdmi_timings. I have seen CRTs that can handle the hdmi_timings in config.txt but not the one in runcommand-onend.sh

**Comment by stuckonretro** [comment]
The three 320x240p timings I have are these:

    320 1 16 30 34 240 1 2 3 22 0 0 0 60 0 6400000 1 #Original Pi2SCART 240p Timing

    320 1 23 30 34 240 1 4 3 15 1 0 0 60 0 6400000 1 #Original RetroTINK Ultimate 240p Timing

    320 1 15 30 42 240 1 4 3 15 1 0 0 60 0 6400000 1 #CRTPi Horizontally Adjusted RetroTINK Ultimate Timing

The 2nd and 3rd are the exact same, with shifted horizontal porching. Are those the one you've seen cause syncing issue? If so, I know the Ultimate can handle the Pi2SCART one -- so I can just porch adjust that and use it universally (and rewrite the 320x200p timing).

**Comment by stuckonretro** [comment]
Alright, I've harmonized the timing from boot to start and end. Please see the most recent commit for more details. Thanks @arcadeforge!

**Comment by arcadeforge** [comment]
Cheers mate, thanks a lot for considering! :)
